title: "ACEA Smart Water Analytics"
locale: en_UK
logo: ![](img/logo_challenge.png)
baseurl: /  

author: 
  name:  @AnnaChirumbolo
  email: anna.chirumbolo@gmail.com

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Anna Chirumbolo

minimal:
  date_format: "%b %-d, %Y"
  
theme: jekyll-theme-minimal
