 theme: jekyll-theme-minimal

# Site wide configuration

title: Dasi Challenge: ACEA Smart Water Analytics
locale: en_UK
logo: # filename of a logo image that has been placed into your images directory

